### ISSUE TITLE
Names on Div Tags

### ISSUE THREAD

**Issue by iamapurba2003** [himangshuishere/Web-Dev#2]
Please go through the Pull Request Generated on your Account & do the needful

## Todo

- [x] Checkout the Pull Request Generated
- [x] Go through the Propose Changes 
- [x] Merge the Proposed Code if everything is alright 
- [x] Write a Issue note to  @iamapurba2003 ... Giving feedback on his changes ...
